/**
 * =====================================================
 * DISCOVERY NOTECRAFT™ - 105 PERGUNTAS ESTRUTURADAS
 * Valor Fiscal - Questionário Completo
 * =====================================================
 */
import { Question } from './types'; // Importando a interface Question conforme instruído.

export const DISCOVERY_QUESTIONS: Question[] = [
  // SEÇÃO 1: Escolha e Priorização de Serviços (6 perguntas)
  {
    id: 'q1-1',
    sectionNumber: 1,
    sectionName: 'Escolha e Priorização de Serviços',
    questionText: 'Qual é a distribuição aproximada do volume de trabalho por especialidade tributária?',
    responseType: 'slider', // Corrigido para 'slider' conforme instrução
    required: true,
    options: ['ICMS (estadual)', 'PIS/COFINS (federal)', 'IR/CSLL (Imposto de Renda e Contribuição Social sobre o Lucro Líquido)', 'ISS (municipal)', 'Folha de pagamento (INSS/FGTS)', 'Outros tributos'],
    additionalField: 'Qual especialidade tem maior demanda de mercado atualmente?'
  },
  {
    id: 'q1-2',
    sectionNumber: 1,
    sectionName: 'Escolha e Priorização de Serviços',
    questionText: 'Qual o percentual de faturamento por tipo de serviço em seu escritório?',
    responseType: 'slider', // Corrigido para 'slider' conforme instrução
    required: true,
    options: ['RCT (Recuperação de Créditos Tributários)', 'Planejamento Tributário', 'Auditoria Tributária', 'Consultoria Tributária', 'Outros serviços'],
  },
  {
    id: 'q1-3',
    sectionNumber: 1,
    sectionName: 'Escolha e Priorização de Serviços',
    questionText: 'Qual especialidade tributária você considera que seu escritório é mais competitivo no mercado?',
    responseType: 'radio',
    required: true,
    options: ['ICMS', 'PIS/COFINS', 'IR/CSLL', 'ISS', 'Folha', 'Outros'],
  },
  {
    id: 'q1-4',
    sectionNumber: 1,
    sectionName: 'Escolha e Priorização de Serviços',
    questionText: 'Quais dos seus serviços você acredita que são mais facilmente padronizáveis ou escaláveis?',
    responseType: 'checkbox',
    required: true,
    options: ['RCT', 'Planejamento', 'Auditoria', 'Consultoria', 'Outros'],
  },
  {
    id: 'q1-5',
    sectionNumber: 1,
    sectionName: 'Escolha e Priorização de Serviços',
    questionText: 'Quais serviços do seu escritório possuem o maior risco jurídico ou de conformidade?',
    responseType: 'checkbox',
    required: true,
    options: ['RCT', 'Planejamento', 'Auditoria', 'Consultoria', 'Outros'],
  },
  {
    id: 'q1-6',
    sectionNumber: 1,
    sectionName: 'Escolha e Priorização de Serviços',
    questionText: 'Qual serviço seu escritório pretende expandir ou focar nos próximos 2 anos?',
    responseType: 'radio',
    required: true,
    options: ['RCT', 'Planejamento', 'Auditoria', 'Consultoria', 'Outros'],
  },

  // SEÇÃO 2: Base de Conhecimento Existente (8 perguntas)
  {
    id: 'q2-1',
    sectionNumber: 2,
    sectionName: 'Base de Conhecimento Existente',
    questionText: 'Onde está armazenada a base de conhecimento (documentos, pareceres, modelos, etc.) do seu escritório?',
    responseType: 'checkbox',
    required: true,
    options: ['Servidor local', 'Nuvem (Google Drive, Dropbox, OneDrive)', 'Sistema de gestão de documentos (DMS)', 'Base de dados específica', 'Outro'],
  },
  {
    id: 'q2-2',
    sectionNumber: 2,
    sectionName: 'Base de Conhecimento Existente',
    questionText: 'Quais tipos de documentos são predominantes na sua base de conhecimento?',
    responseType: 'checkbox',
    required: true,
    options: ['Pareceres', 'Modelos de petições', 'Manuais internos', 'Legislação comentada', 'Jurisprudência selecionada', 'Contratos', 'Relatórios de auditoria', 'Emails e comunicações', 'Outros'],
  },
  {
    id: 'q2-3',
    sectionNumber: 2,
    sectionName: 'Base de Conhecimento Existente',
    questionText: 'Qual a quantidade aproximada de documentos que compõem a sua base de conhecimento?',
    responseType: 'radio',
    required: true,
    options: ['Menos de 100', '100-500', '501-1000', 'Mais de 1000'],
  },
  {
    id: 'q2-4',
    sectionNumber: 2,
    sectionName: 'Base de Conhecimento Existente',
    questionText: 'Qual sistema ou método vocês utilizam para organizar e buscar informações na base de conhecimento?',
    responseType: 'radio',
    required: true,
    options: ['Pastas e arquivos manuais', 'Indexação por palavras-chave', 'Sistema de busca interna', 'Tagging e metadados', 'Busca avançada com IA', 'Não há sistema formal'],
  },
  {
    id: 'q2-5',
    sectionNumber: 2,
    sectionName: 'Base de Conhecimento Existente',
    questionText: 'Existe uma categorização formal dos documentos por tributos, setores ou temas?',
    responseType: 'checkbox',
    required: true,
    options: ['Sim, por tributo', 'Sim, por setor de atuação', 'Sim, por tipo de serviço', 'Não há categorização formal', 'Parcialmente'],
  },
  {
    id: 'q2-6',
    sectionNumber: 2,
    sectionName: 'Base de Conhecimento Existente',
    questionText: 'Quem é o responsável por manter e atualizar a base de conhecimento do escritório?',
    responseType: 'radio',
    required: true,
    options: ['Equipe jurídica/tributária', 'Equipe de P&D/Inovação', 'Um profissional dedicado', 'Não há um responsável fixo', 'Outro'],
  },
  {
    id: 'q2-7',
    sectionNumber: 2,
    sectionName: 'Base de Conhecimento Existente',
    questionText: 'Como é o controle de acesso à base de conhecimento?',
    responseType: 'radio',
    required: true,
    options: ['Restrito (por cargo/departamento)', 'Aberto a todos os colaboradores', 'Apenas por solicitação', 'Não há controle formal'],
  },
  {
    id: 'q2-8',
    sectionNumber: 2,
    sectionName: 'Base de Conhecimento Existente',
    questionText: 'Há um orçamento dedicado para a gestão e melhoria da base de conhecimento?',
    responseType: 'radio',
    required: true,
    options: ['Sim, anual', 'Sim, por projeto', 'Não', 'Em análise'],
  },

  // SEÇÃO 3: Visão de Automação e IA (8 perguntas)
  {
    id: 'q3-1',
    sectionNumber: 3,
    sectionName: 'Visão de Automação e IA',
    questionText: 'Quais processos em seu escritório já estão parcial ou totalmente automatizados?',
    responseType: 'checkbox',
    required: true,
    options: ['Emissão de guias', 'Cálculo de tributos', 'Conferência de documentos fiscais', 'Preenchimento de formulários', 'Geração de relatórios simples', 'Agendamento de reuniões', 'Não possuímos processos automatizados', 'Outros'],
  },
  {
    id: 'q3-2',
    sectionNumber: 3,
    sectionName: 'Visão de Automação e IA',
    questionText: 'Quais ferramentas de Inteligência Artificial (IA) seu escritório já testou ou utiliza atualmente?',
    responseType: 'checkbox',
    required: true,
    options: ['ChatGPT', 'Google Bard/Gemini', 'Microsoft Copilot', 'Ferramentas de IA para análise de documentos', 'Ferramentas de IA para pesquisa jurídica', 'Nenhuma', 'Outras'],
  },
  {
    id: 'q3-3',
    sectionNumber: 3,
    sectionName: 'Visão de Automação e IA',
    questionText: 'Quais áreas ou processos do seu escritório você considera mais candidatas à automação ou aplicação de IA?',
    responseType: 'checkbox',
    required: true,
    options: ['Pesquisa jurídica', 'Análise de documentos', 'Geração de relatórios', 'Atendimento ao cliente (FAQ)', 'Prospecção comercial', 'Gestão de projetos', 'Não sabemos', 'Outros'],
  },
  {
    id: 'q3-4',
    sectionNumber: 3,
    sectionName: 'Visão de Automação e IA',
    questionText: 'Qual é o maior receio ou preocupação do seu escritório em relação à adoção de IA?',
    responseType: 'radio',
    required: true,
    options: ['Custo de implementação', 'Segurança dos dados', 'Aceitação da equipe', 'Perda de empregos', 'Qualidade/precisão da IA', 'Manutenção da tecnologia', 'Outro'],
  },
  {
    id: 'q3-5',
    sectionNumber: 3,
    sectionName: 'Visão de Automação e IA',
    questionText: 'Quais os principais ganhos seu escritório espera obter com a implementação de IA?',
    responseType: 'checkbox',
    required: true,
    options: ['Redução de tempo', 'Aumento da produtividade', 'Melhora na precisão', 'Redução de custos', 'Aumento da satisfação do cliente', 'Abertura para novos serviços', 'Não sei', 'Outros'],
  },
  {
    id: 'q3-6',
    sectionNumber: 3,
    sectionName: 'Visão de Automação e IA',
    questionText: 'Como você avalia a reação geral da sua equipe à ideia de implementar IA no trabalho?',
    responseType: 'radio',
    required: true,
    options: ['Entusiasmados e curiosos', 'Céticos, mas abertos a aprender', 'Resistentes à mudança', 'Preocupados com o futuro', 'Não há uma opinião clara'],
  },
  {
    id: 'q3-7',
    sectionNumber: 3,
    sectionName: 'Visão de Automação e IA',
    questionText: 'Existe um "sponsor" ou líder interno que esteja à frente de projetos de tecnologia e inovação com IA?',
    responseType: 'radio',
    required: true,
    options: ['Diretoria/Sócios', 'Líder de tecnologia/inovação', 'Gestores de área', 'Não há um sponsor definido'],
  },
  {
    id: 'q3-8',
    sectionNumber: 3,
    sectionName: 'Visão de Automação e IA',
    questionText: 'Qual o principal critério para aprovar um investimento significativo em tecnologia/IA no seu escritório?',
    responseType: 'radio',
    required: true,
    options: ['ROI (Retorno sobre Investimento)', 'Redução de custos', 'Aumento de receita', 'Melhora na eficiência', 'Satisfação do cliente', 'Estratégia de mercado', 'Outro'],
  },

  // SEÇÃO 4: Percepção de Valor (6 perguntas)
  {
    id: 'q4-1',
    sectionNumber: 4,
    sectionName: 'Percepção de Valor',
    questionText: 'Como seu escritório mede o sucesso dos seus serviços e da operação como um todo?',
    responseType: 'checkbox',
    required: true,
    options: ['Faturamento', 'Lucratividade', 'Produtividade da equipe', 'Satisfação do cliente (NPS)', 'Taxa de retenção de clientes', 'Número de novos clientes', 'Número de projetos concluídos', 'Outros'],
  },
  {
    id: 'q4-2',
    sectionNumber: 4,
    sectionName: 'Percepção de Valor',
    questionText: 'Qual valor mínimo uma solução de IA precisaria gerar para ser considerada um investimento válido para o seu escritório?',
    responseType: 'radio',
    required: true,
    options: ['Redução de 10% do tempo em processos', 'Redução de 20% do tempo em processos', 'Redução de 30% ou mais do tempo em processos', 'Aumento de 5% no faturamento', 'Aumento de 10% no faturamento', 'Melhora na qualidade de vida da equipe', 'Outro'],
  },
  {
    id: 'q4-3',
    sectionNumber: 4,
    sectionName: 'Percepção de Valor',
    questionText: 'Qual você considera o maior diferencial competitivo do seu escritório no mercado?',
    responseType: 'radio',
    required: true,
    options: ['Preço', 'Qualidade técnica', 'Atendimento personalizado', 'Tecnologia/inovação', 'Networking/Relacionamento', 'Velocidade na entrega', 'Outro'],
  },
  {
    id: 'q4-4',
    sectionNumber: 4,
    sectionName: 'Percepção de Valor',
    questionText: 'Como seu escritório precifica os serviços oferecidos aos clientes?',
    responseType: 'checkbox',
    required: true,
    options: ['Por hora trabalhada', 'Por projeto/fixo', 'Por valor agregado/sucesso', 'Assinatura mensal', 'Combinado (híbrido)', 'Outro'],
  },
  {
    id: 'q4-5',
    sectionNumber: 4,
    sectionName: 'Percepção de Valor',
    questionText: 'Por que clientes escolhem o seu escritório em detrimento da concorrência?',
    responseType: 'radio',
    required: true,
    options: ['Recomendação (boca a boca)', 'Reputação no mercado', 'Marketing digital', 'Networking pessoal', 'Valor do serviço', 'Experiência prévia', 'Outro'],
  },
  {
    id: 'q4-6',
    sectionNumber: 4,
    sectionName: 'Percepção de Valor',
    questionText: 'Se você pudesse automatizar um único processo para impressionar seus clientes ou equipe, qual seria?',
    responseType: 'text',
    required: true,
    placeholder: 'Descreva qual processo, se automatizado, causaria maior impacto.',
  },

  // SEÇÃO 5: Cenário Comercial Futuro (6 perguntas)
  {
    id: 'q5-1',
    sectionNumber: 5,
    sectionName: 'Cenário Comercial Futuro',
    questionText: 'Seu escritório tem uma meta de crescimento específica para os próximos 1-3 anos?',
    responseType: 'checkbox',
    required: true,
    options: ['Sim, de X% ao ano (ex: 20%)', 'Sim, de Y novos clientes', 'Não há uma meta formal definida', 'Em processo de definição'],
  },
  {
    id: 'q5-2',
    sectionNumber: 5,
    sectionName: 'Cenário Comercial Futuro',
    questionText: 'Qual é o foco principal da sua meta de crescimento?',
    responseType: 'radio',
    required: true,
    options: ['Aumento de receita', 'Aumento da base de clientes', 'Expansão geográfica', 'Lançamento de novos serviços', 'Melhora na rentabilidade', 'Outro'],
  },
  {
    id: 'q5-3',
    sectionNumber: 5,
    sectionName: 'Cenário Comercial Futuro',
    questionText: 'Quais são os planos estratégicos de longo prazo do seu escritório (5+ anos)?',
    responseType: 'radio',
    required: true,
    options: ['Expansão de serviços', 'Internacionalização', 'Aquisição de outras empresas', 'Desenvolvimento de tecnologia própria', 'Foco em nicho de mercado', 'Não temos planos de longo prazo definidos'],
  },
  {
    id: 'q5-4',
    sectionNumber: 5,
    sectionName: 'Cenário Comercial Futuro',
    questionText: 'Qual você considera o maior gargalo atual para o crescimento do seu escritório?',
    responseType: 'radio',
    required: true,
    options: ['Captação de novos clientes', 'Retenção de talentos', 'Capacidade operacional', 'Burocracia/Regulamentação', 'Falta de tecnologia', 'Concorrência', 'Outro'],
  },
  {
    id: 'q5-5',
    sectionNumber: 5,
    sectionName: 'Cenário Comercial Futuro',
    questionText: 'Como você enxerga a evolução do mercado tributário nos próximos anos?',
    responseType: 'checkbox',
    required: true,
    options: ['Mais complexo', 'Mais digital', 'Mais competitivo', 'Mais consultivo', 'Mais regulado', 'Outras tendências'],
  },
  {
    id: 'q5-6',
    sectionNumber: 5,
    sectionName: 'Cenário Comercial Futuro',
    questionText: 'Descreva um cenário ideal para o seu escritório daqui a 5 anos, com a IA já totalmente integrada.',
    responseType: 'text',
    required: true,
    placeholder: 'Descreva como a IA transformaria seu negócio em um cenário ideal.',
  },

  // SEÇÃO 6: Ecossistema Tecnológico (6 perguntas)
  {
    id: 'q6-1',
    sectionNumber: 6,
    sectionName: 'Ecossistema Tecnológico',
    questionText: 'Quais sistemas ou softwares seu escritório utiliza diariamente para a gestão e operação?',
    responseType: 'checkbox',
    required: true,
    options: ['ERP (ex: Protheus, SAP)', 'Software contábil (ex: Domínio, Alterdata)', 'Software jurídico (ex: Astrea, SAJ)', 'CRM (ex: Salesforce, Hubspot)', 'Ferramentas de produtividade (ex: Office 365, Google Workspace)', 'Plataformas de comunicação (ex: Slack, Teams)', 'Nenhum específico', 'Outros'],
  },
  {
    id: 'q6-2',
    sectionNumber: 6,
    sectionName: 'Ecossistema Tecnológico',
    questionText: 'Como é a integração entre os diferentes sistemas e softwares utilizados pelo seu escritório?',
    responseType: 'radio',
    required: true,
    options: ['Totalmente integrados', 'Parcialmente integrados (algumas ferramentas)', 'Não integrados, processos manuais', 'Em processo de integração'],
  },
  {
    id: 'q6-3',
    sectionNumber: 6,
    sectionName: 'Ecossistema Tecnológico',
    questionText: 'Quem é o responsável pela gestão e estratégia de tecnologia no seu escritório?',
    responseType: 'radio',
    required: true,
    options: ['TI interna', 'Consultoria externa', 'Um dos sócios/diretores', 'Nenhum responsável formal', 'Equipe multidisciplinar'],
  },
  {
    id: 'q6-4',
    sectionNumber: 6,
    sectionName: 'Ecossistema Tecnológico',
    questionText: 'Com que frequência os sistemas e softwares utilizados são atualizados e recebem manutenção?',
    responseType: 'radio',
    required: true,
    options: ['Sistemas atualizam automaticamente', 'Atualizações agendadas e controladas', 'Atualizações esporádicas/quando necessário', 'Não há um processo formal'],
  },
  {
    id: 'q6-5',
    sectionNumber: 6,
    sectionName: 'Ecossistema Tecnológico',
    questionText: 'Qual o maior problema ou desafio relacionado à tecnologia que seu escritório enfrenta atualmente?',
    responseType: 'radio',
    required: true,
    options: ['Sistemas desatualizados', 'Falta de integração', 'Custo das licenças', 'Segurança dos dados', 'Suporte técnico', 'Complexidade de uso', 'Outro'],
  },
  {
    id: 'q6-6',
    sectionNumber: 6,
    sectionName: 'Ecossistema Tecnológico',
    questionText: 'Se você pudesse resolver um problema tecnológico com um "estalar de dedos", qual seria?',
    responseType: 'text',
    required: true,
    placeholder: 'Qual problema tecnológico você eliminaria instantaneamente se pudesse?',
  },

  // SEÇÃO 7: Estrutura Organizacional (8 perguntas)
  {
    id: 'q7-1',
    sectionNumber: 7,
    sectionName: 'Estrutura Organizacional',
    questionText: 'Qual o tamanho total da equipe do seu escritório (incluindo sócios, advogados, estagiários, administrativos, etc.)?',
    responseType: 'number',
    required: true,
    placeholder: 'Número total de colaboradores',
  },
  {
    id: 'q7-2',
    sectionNumber: 7,
    sectionName: 'Estrutura Organizacional',
    questionText: 'Quantas filiais ou unidades de operação seu escritório possui (incluindo sedes remotas)?',
    responseType: 'number',
    required: true,
    placeholder: 'Número de unidades físicas ou remotas',
  },
  {
    id: 'q7-3',
    sectionNumber: 7,
    sectionName: 'Estrutura Organizacional',
    questionText: 'Se o escritório possui mais de uma unidade, como você avalia o desempenho de cada uma?',
    responseType: 'text',
    required: true,
    placeholder: 'Descreva brevemente o desempenho das suas unidades (se houver mais de uma).',
  },
  {
    id: 'q7-4',
    sectionNumber: 7,
    sectionName: 'Estrutura Organizacional',
    questionText: 'Qual a faixa de idade predominante da sua equipe?',
    responseType: 'radio',
    required: true,
    options: ['Até 25 anos', '26-35 anos', '36-45 anos', 'Acima de 45 anos', 'Variado, sem média predominante'],
  },
  {
    id: 'q7-5',
    sectionNumber: 7,
    sectionName: 'Estrutura Organizacional',
    questionText: 'Como você descreveria a rotatividade da equipe no seu escritório?',
    responseType: 'radio',
    required: true,
    options: ['Muito baixa (quase ninguém sai)', 'Baixa (menos de 10% ao ano)', 'Média (10-25% ao ano)', 'Alta (acima de 25% ao ano)'],
  },
  {
    id: 'q7-6',
    sectionNumber: 7,
    sectionName: 'Estrutura Organizacional',
    questionText: 'Seu escritório possui um plano de cargos e salários estruturado?',
    responseType: 'radio',
    required: true,
    options: ['Sim, estruturado', 'Sim, mas informal', 'Não, em desenvolvimento', 'Não, sem planos'],
  },
  {
    id: 'q7-7',
    sectionNumber: 7,
    sectionName: 'Estrutura Organizacional',
    questionText: 'Quais são os principais métodos de treinamento e capacitação utilizados para a equipe?',
    responseType: 'checkbox',
    required: true,
    options: ['Interno (palestras, workshops)', 'Externo (cursos, pós-graduação)', 'Online (plataformas EAD)', 'Mentoria/coaching', 'Não há programa formal', 'Outros'],
  },
  {
    id: 'q7-8',
    sectionNumber: 7,
    sectionName: 'Estrutura Organizacional',
    questionText: 'Qual o maior desafio de gestão de pessoas que seu escritório enfrenta atualmente?',
    responseType: 'radio',
    required: true,
    options: ['Engajamento da equipe', 'Retenção de talentos', 'Comunicação interna', 'Definição de metas e KPIs', 'Gestão de conflitos', 'Produtividade individual', 'Outro'],
  },

  // SEÇÃO 8: Performance e KPIs (8 perguntas)
  {
    id: 'q8-1',
    sectionNumber: 8,
    sectionName: 'Performance e KPIs',
    questionText: 'Quais números ou indicadores seu escritório acompanha semanalmente?',
    responseType: 'checkbox',
    required: true,
    options: ['Faturamento', 'Número de novos clientes', 'Despesas', 'Fluxo de caixa', 'Horas trabalhadas', 'Status de projetos', 'Nenhum específico', 'Outros'],
  },
  {
    id: 'q8-2',
    sectionNumber: 8,
    sectionName: 'Performance e KPIs',
    questionText: 'Como seu escritório acompanha esses números e indicadores?',
    responseType: 'radio',
    required: true,
    options: ['Planilhas (Excel/Google Sheets)', 'Sistema de gestão (ERP/CRM)', 'Dashboards personalizados', 'Reuniões semanais', 'Visualização manual', 'Outro'],
  },
  {
    id: 'q8-3',
    sectionNumber: 8,
    sectionName: 'Performance e KPIs',
    questionText: 'Qual o KPI (Key Performance Indicator) mais importante para o seu escritório atualmente?',
    responseType: 'radio',
    required: true,
    options: ['Faturamento Bruto', 'Lucratividade Líquida', 'Margem de Lucro', 'CAC (Custo de Aquisição de Cliente)', 'LTV (Lifetime Value)', 'NPS (Net Promoter Score)', 'Produtividade por colaborador', 'Outro'],
  },
  {
    id: 'q8-4',
    sectionNumber: 8,
    sectionName: 'Performance e KPIs',
    questionText: 'O escritório mede a produtividade individual de seus colaboradores?',
    responseType: 'radio',
    required: true,
    options: ['Sim, por horas faturáveis', 'Sim, por entregas/projetos', 'Sim, por metas alcançadas', 'Não há medição formal', 'Em desenvolvimento'],
  },
  {
    id: 'q8-5',
    sectionNumber: 8,
    sectionName: 'Performance e KPIs',
    questionText: 'Como seu escritório mede a satisfação de seus clientes?',
    responseType: 'checkbox',
    required: true,
    options: ['Pesquisas de satisfação (NPS)', 'Feedback direto (reuniões)', 'Análise de reclamações', 'Taxa de retenção', 'Testemunhos/depoimentos', 'Não medimos formalmente', 'Outros'],
  },
  {
    id: 'q8-6',
    sectionNumber: 8,
    sectionName: 'Performance e KPIs',
    questionText: 'Qual a sua taxa de conversão atual (leads em clientes)?',
    responseType: 'radio',
    required: true,
    options: ['Abaixo de 5%', 'Entre 5-10%', 'Entre 10-20%', 'Acima de 20%', 'Não sei/Não medimos'],
  },
  {
    id: 'q8-7',
    sectionNumber: 8,
    sectionName: 'Performance e KPIs',
    questionText: 'Seu escritório realiza controle de tempo gasto por projeto ou cliente?',
    responseType: 'radio',
    required: true,
    options: ['Sim, detalhado por tarefa', 'Sim, por projeto total', 'Não, apenas estimamos', 'Não há controle formal'],
  },
  {
    id: 'q8-8',
    sectionNumber: 8,
    sectionName: 'Performance e KPIs',
    questionText: 'Qual indicador você gostaria que a IA melhorasse prioritariamente em seu escritório?',
    responseType: 'radio',
    required: true,
    options: ['Produtividade da equipe', 'Precisão das análises', 'Velocidade na entrega', 'Satisfação do cliente', 'Custo operacional', 'Receita/Faturamento', 'Outro'],
  },

  // SEÇÃO 9: Marketing e Prospecção (7 perguntas)
  {
    id: 'q9-1',
    sectionNumber: 9,
    sectionName: 'Marketing e Prospecção',
    questionText: 'Quais são os principais canais de aquisição de clientes do seu escritório?',
    responseType: 'checkbox',
    required: true,
    options: ['Boca a boca/indicação', 'Marketing de conteúdo (blog, artigos)', 'Mídias sociais (LinkedIn, Instagram)', 'Eventos/Webinars', 'Prospecção ativa (cold calling/email)', 'Parcerias estratégicas', 'Anúncios pagos (Google Ads, Social Ads)', 'Outros'],
  },
  {
    id: 'q9-2',
    sectionNumber: 9,
    sectionName: 'Marketing e Prospecção',
    questionText: 'Como é a estrutura do seu time de vendas ou prospecção?',
    responseType: 'text',
    required: true,
    placeholder: 'Descreva a estrutura do seu time de vendas (ex: número de vendedores, função, etc.).',
  },
  {
    id: 'q9-3',
    sectionNumber: 9,
    sectionName: 'Marketing e Prospecção',
    questionText: 'Como o time de vendas (ou quem prospecta) é remunerado?',
    responseType: 'checkbox',
    required: true,
    options: ['Salário fixo', 'Comissão sobre vendas', 'Bônus por meta', 'Participação nos lucros', 'Misto (fixo + comissão/bônus)', 'Outro'],
  },
  {
    id: 'q9-4',
    sectionNumber: 9,
    sectionName: 'Marketing e Prospecção',
    questionText: 'Qual canal de aquisição de clientes gera o maior LTV (Lifetime Value) para o seu escritório?',
    responseType: 'radio',
    required: true,
    options: ['Indicações', 'Marketing de conteúdo', 'Prospecção ativa', 'Eventos', 'Parcerias', 'Anúncios pagos', 'Não sei/Não medimos'],
  },
  {
    id: 'q9-5',
    sectionNumber: 9,
    sectionName: 'Marketing e Prospecção',
    questionText: 'Qual o custo de aquisição de cliente (CAC) aproximado do seu escritório?',
    responseType: 'radio',
    required: true,
    options: ['Até R$500', 'R$501 - R$1.500', 'R$1.501 - R$5.000', 'Acima de R$5.000', 'Não sei/Não medimos'],
  },
  {
    id: 'q9-6',
    sectionNumber: 9,
    sectionName: 'Marketing e Prospecção',
    questionText: 'Qual o tempo médio entre o primeiro contato com um lead e o fechamento do contrato?',
    responseType: 'radio',
    required: true,
    options: ['Menos de 1 semana', '1-2 semanas', '2-4 semanas', 'Mais de 1 mês', 'Muito variável'],
  },
  {
    id: 'q9-7',
    sectionNumber: 9,
    sectionName: 'Marketing e Prospecção',
    questionText: 'Qual é o principal gargalo comercial que seu escritório enfrenta atualmente?',
    responseType: 'radio',
    required: true,
    options: ['Qualificação de leads', 'Velocidade do ciclo de vendas', 'Fechamento de propostas', 'Pós-venda e retenção', 'Capacitação da equipe', 'Volume de leads', 'Outro'],
  },

  // SEÇÃO 10: Fontes Jurídicas e Pesquisa (6 perguntas)
  {
    id: 'q10-1',
    sectionNumber: 10,
    sectionName: 'Fontes Jurídicas e Pesquisa',
    questionText: 'Quais sites, sistemas ou ferramentas são mais utilizados para pesquisa jurídica e tributária no seu escritório?',
    responseType: 'checkbox',
    required: true,
    options: ['Legislação oficial (planaltos.gov.br)', 'Sistemas de jurisprudência (TRFs, STJ, STF)', 'Bases de dados tributárias (IOB, Thomson Reuters, Sefaz)', 'Doutrina e periódicos jurídicos', 'Pesquisa em buscadores gerais (Google)', 'Nenhum específico', 'Outros'],
  },
  {
    id: 'q10-2',
    sectionNumber: 10,
    sectionName: 'Fontes Jurídicas e Pesquisa',
    questionText: 'Como seu escritório acompanha as mudanças legislativas e jurisprudenciais relevantes?',
    responseType: 'checkbox',
    required: true,
    options: ['Alertas de sistemas jurídicos', 'Boletins informativos', 'Periódicos especializados', 'Associações/sindicatos', 'Monitoramento manual', 'Não acompanhamos formalmente', 'Outros'],
  },
  {
    id: 'q10-3',
    sectionNumber: 10,
    sectionName: 'Fontes Jurídicas e Pesquisa',
    questionText: 'Qual percentual do tempo dos profissionais é gasto em pesquisa jurídica e tributária?',
    responseType: 'radio',
    required: true,
    options: ['Menos de 10% do tempo', '10-25% do tempo', '25-50% do tempo', 'Mais de 50% do tempo'],
  },
  {
    id: 'q10-4',
    sectionNumber: 10,
    sectionName: 'Fontes Jurídicas e Pesquisa',
    questionText: 'Quem são os principais responsáveis pela pesquisa jurídica e tributária no escritório?',
    responseType: 'radio',
    required: true,
    options: ['Advogados seniores', 'Advogados juniores/estagiários', 'Equipe de apoio/pesquisadores', 'Todos os profissionais', 'Outro'],
  },
  {
    id: 'q10-5',
    sectionNumber: 10,
    sectionName: 'Fontes Jurídicas e Pesquisa',
    questionText: 'Qual a maior dificuldade enfrentada durante o processo de pesquisa jurídica e tributária?',
    responseType: 'radio',
    required: true,
    options: ['Volume de informações', 'Encontrar fontes confiáveis', 'Tempo gasto', 'Interpretação da legislação', 'Falta de ferramentas adequadas', 'Organização das descobertas', 'Outro'],
  },
  {
    id: 'q10-6',
    sectionNumber: 10,
    sectionName: 'Fontes Jurídicas e Pesquisa',
    questionText: 'Qual o maior benefício que a IA poderia trazer para o processo de pesquisa jurídica e tributária no seu escritório?',
    responseType: 'radio',
    required: true,
    options: ['Velocidade na busca', 'Precisão das respostas', 'Análise de grandes volumes de dados', 'Identificação de padrões', 'Economia de tempo', 'Atualização constante', 'Outro'],
  },

  // SEÇÃO 11: Maturidade Digital (6 perguntas)
  {
    id: 'q11-1',
    sectionNumber: 11,
    sectionName: 'Maturidade Digital',
    questionText: 'Como você avalia o nível de maturidade tecnológica do seu escritório?',
    responseType: 'radio',
    required: true,
    options: ['Básico (uso de ferramentas essenciais)', 'Intermediário (alguma automação e uso de sistemas)', 'Avançado (uso de IA, integrações, foco em inovação)', 'Pioneiro (líder em tecnologia no setor)', 'Não sei avaliar'],
  },
  {
    id: 'q11-2',
    sectionNumber: 11,
    sectionName: 'Maturidade Digital',
    questionText: 'Qual a receptividade geral do seu escritório a novas tecnologias e inovações?',
    responseType: 'radio',
    required: true,
    options: ['Alta (sempre buscando novidades)', 'Média (abertos, mas cautelosos)', 'Baixa (resistência à mudança)', 'Depende do custo/benefício'],
  },
  {
    id: 'q11-3',
    sectionNumber: 11,
    sectionName: 'Maturidade Digital',
    questionText: 'Quem toma as decisões sobre investimentos em tecnologia no seu escritório?',
    responseType: 'radio',
    required: true,
    options: ['Diretoria/Sócios', 'Comitê de inovação', 'TI interna', 'Consultoria externa', 'Não há processo formal'],
  },
  {
    id: 'q11-4',
    sectionNumber: 11,
    sectionName: 'Maturidade Digital',
    questionText: 'Existe um orçamento anual dedicado para tecnologia e inovação no escritório?',
    responseType: 'radio',
    required: true,
    options: ['Menos de 1% do faturamento', '1-3% do faturamento', '3-5% do faturamento', 'Mais de 5% do faturamento', 'Não há orçamento dedicado'],
  },
  {
    id: 'q11-5',
    sectionNumber: 11,
    sectionName: 'Maturidade Digital',
    questionText: 'Como é realizada a política de backup e segurança dos dados do escritório?',
    responseType: 'radio',
    required: true,
    options: ['Automatizados e regulares', 'Manuais e regulares', 'Esporádicos', 'Não há processo formal', 'Não sei'],
  },
  {
    id: 'q11-6',
    sectionNumber: 11,
    sectionName: 'Maturidade Digital',
    questionText: 'Se você pudesse implementar UMA tecnologia em seu escritório amanhã, qual seria e por quê?',
    responseType: 'text',
    required: true,
    placeholder: 'Se você pudesse implementar UMA tecnologia amanhã, qual seria e por quê?',
  },

  // SEÇÃO 12: Captura de Conversas (6 perguntas)
  {
    id: 'q12-1',
    sectionNumber: 12,
    sectionName: 'Captura de Conversas',
    questionText: 'Seu escritório costuma gravar reuniões (internas e/ou com clientes)?',
    responseType: 'radio',
    required: true,
    options: ['Sempre', 'Ocasionalmente (com consentimento)', 'Raramente', 'Nunca'],
  },
  {
    id: 'q12-2',
    sectionNumber: 12,
    sectionName: 'Captura de Conversas',
    questionText: 'Quais plataformas de reuniões remotas seu escritório mais utiliza?',
    responseType: 'checkbox',
    required: true,
    options: ['Google Meet', 'Zoom', 'Microsoft Teams', 'Webex', 'Outra', 'Não usamos plataformas de reunião remota'],
  },
  {
    id: 'q12-3',
    sectionNumber: 12,
    sectionName: 'Captura de Conversas',
    questionText: 'Vocês transcrevem o conteúdo das reuniões gravadas?',
    responseType: 'radio',
    required: true,
    options: ['Sim, manual', 'Sim, com ferramentas automáticas', 'Não, mas gostaríamos', 'Não'],
  },
  {
    id: 'q12-4',
    sectionNumber: 12,
    sectionName: 'Captura de Conversas',
    questionText: 'Como seu escritório documenta as decisões e os próximos passos definidos em reuniões?',
    responseType: 'checkbox',
    required: true,
    options: ['Atas de reunião', 'Emails de follow-up', 'Sistemas de gestão de projetos', 'Notas informais', 'Não há documentação formal', 'Outros'],
  },
  {
    id: 'q12-5',
    sectionNumber: 12,
    sectionName: 'Captura de Conversas',
    questionText: 'Quem é o responsável por documentar e garantir o acompanhamento dos acordos e decisões de reuniões?',
    responseType: 'radio',
    required: true,
    options: ['Secretariado/Apoio', 'Líder do projeto/Advogado responsável', 'A pessoa que propôs o acordo', 'Não há um responsável fixo'],
  },
  {
    id: 'q12-6',
    sectionNumber: 12,
    sectionName: 'Captura de Conversas',
    questionText: 'Qual a utilidade de ter uma IA para transcrever e resumir reuniões para o seu escritório?',
    responseType: 'radio',
    required: true,
    options: ['Muito útil (alta prioridade)', 'Útil (média prioridade)', 'Pouco útil (baixa prioridade)', 'Não vejo utilidade'],
  },

  // SEÇÃO 13: Suporte ao Cliente (6 perguntas)
  {
    id: 'q13-1',
    sectionNumber: 13,
    sectionName: 'Suporte ao Cliente',
    questionText: 'Quais são os principais canais pelos quais os clientes do seu escritório entram em contato para tirar dúvidas ou fazer solicitações?',
    responseType: 'checkbox',
    required: true,
    options: ['Email', 'Telefone', 'WhatsApp', 'Sistema de tickets/chat no site', 'Reuniões presenciais', 'Mídias sociais', 'Outros'],
  },
  {
    id: 'q13-2',
    sectionNumber: 13,
    sectionName: 'Suporte ao Cliente',
    questionText: 'Qual o tempo médio de resposta do seu escritório às solicitações e dúvidas dos clientes?',
    responseType: 'radio',
    required: true,
    options: ['Menos de 1 hora', '1-4 horas', '4-8 horas', 'Mais de 8 horas', 'Varia muito'],
  },
  {
    id: 'q13-3',
    sectionNumber: 13,
    sectionName: 'Suporte ao Cliente',
    questionText: 'Seu escritório utiliza algum sistema de tickets ou chamados para gerenciar o suporte ao cliente?',
    responseType: 'radio',
    required: true,
    options: ['Sim, dedicado', 'Sim, parte de um CRM', 'Não, usamos email/WhatsApp', 'Em avaliação'],
  },
  {
    id: 'q13-4',
    sectionNumber: 13,
    sectionName: 'Suporte ao Cliente',
    questionText: 'Quem são os principais responsáveis por responder às dúvidas e solicitações dos clientes?',
    responseType: 'checkbox',
    required: true,
    options: ['Equipe de atendimento', 'Advogados/Consultores', 'Secretariado', 'Sistemas de FAQ/chatbot', 'Todos', 'Outros'],
  },
  {
    id: 'q13-5',
    sectionNumber: 13,
    sectionName: 'Suporte ao Cliente',
    questionText: 'Qual o tipo de dúvida ou solicitação mais comum que os clientes fazem ao seu escritório?',
    responseType: 'radio',
    required: true,
    options: ['Andamento de processos', 'Status de pagamentos/faturas', 'Dúvidas técnicas/jurídicas', 'Solicitação de documentos', 'Informações gerais sobre serviços', 'Outro'],
  },
  {
    id: 'q13-6',
    sectionNumber: 13,
    sectionName: 'Suporte ao Cliente',
    questionText: 'Qual a utilidade de ter uma IA para responder a dúvidas básicas e repetitivas dos clientes?',
    responseType: 'radio',
    required: true,
    options: ['Muito útil (liberaria equipe)', 'Útil (otimizaria tempo)', 'Pouco útil (preferimos contato humano)', 'Não vejo utilidade'],
  },

  // SEÇÃO 14: Comunicação Proativa (6 perguntas)
  {
    id: 'q14-1',
    sectionNumber: 14,
    sectionName: 'Comunicação Proativa',
    questionText: 'Seu escritório realiza algum tipo de acompanhamento proativo com os clientes?',
    responseType: 'radio',
    required: true,
    options: ['Sim, com frequência definida', 'Sim, apenas em marcos importantes', 'Não, apenas quando solicitados', 'Em desenvolvimento'],
  },
  {
    id: 'q14-2',
    sectionNumber: 14,
    sectionName: 'Comunicação Proativa',
    questionText: 'Como seu escritório comunica mudanças legislativas ou notícias relevantes para seus clientes?',
    responseType: 'checkbox',
    required: true,
    options: ['Newsletters/Boletins', 'Alertas personalizados', 'Reuniões específicas', 'Redes sociais', 'Não comunicamos proativamente', 'Outros'],
  },
  {
    id: 'q14-3',
    sectionNumber: 14,
    sectionName: 'Comunicação Proativa',
    questionText: 'Seu escritório envia relatórios periódicos de andamento ou resultados aos clientes?',
    responseType: 'radio',
    required: true,
    options: ['Sim, mensais', 'Sim, trimestrais', 'Sim, anuais', 'Não, apenas sob demanda', 'Não oferecemos'],
  },
  {
    id: 'q14-4',
    sectionNumber: 14,
    sectionName: 'Comunicação Proativa',
    questionText: 'Como seu escritório mede a satisfação do cliente ao longo da execução de um projeto ou serviço?',
    responseType: 'checkbox',
    required: true,
    options: ['Pesquisas intermediárias', 'Reuniões de checkpoint', 'Feedback verbal contínuo', 'Não medimos durante o projeto', 'Outros'],
  },
  {
    id: 'q14-5',
    sectionNumber: 14,
    sectionName: 'Comunicação Proativa',
    questionText: 'Qual a frequência de contato ideal que você acredita ser mais eficiente para manter os clientes engajados e informados?',
    responseType: 'radio',
    required: true,
    options: ['Semanal', 'Quinzenal', 'Mensal', 'Trimestral', 'A cada milestone do projeto'],
  },
  {
    id: 'q14-6',
    sectionNumber: 14,
    sectionName: 'Comunicação Proativa',
    questionText: 'Qual a utilidade de ter uma IA para gerar relatórios automáticos de andamento e resultados para os clientes?',
    responseType: 'radio',
    required: true,
    options: ['Muito útil (alta prioridade)', 'Útil (média prioridade)', 'Pouco útil (preferimos manuais)', 'Não vejo utilidade'],
  },

  // SEÇÃO 15: Expansão e Plataformização (6 perguntas)
  {
    id: 'q15-1',
    sectionNumber: 15,
    sectionName: 'Expansão e Plataformização',
    questionText: 'Seu escritório tem planos de franquear sua metodologia ou modelo de negócio?',
    responseType: 'radio',
    required: true,
    options: ['Sim, já estamos avaliando', 'Sim, no futuro', 'Não, não é nosso foco', 'Talvez, se houver demanda'],
  },
  {
    id: 'q15-2',
    sectionNumber: 15,
    sectionName: 'Expansão e Plataformização',
    questionText: 'Existe interesse em transformar alguns dos seus serviços em produtos digitais escaláveis?',
    responseType: 'radio',
    required: true,
    options: ['Sim, já temos produtos', 'Sim, estamos desenvolvendo', 'Não, não é nosso foco', 'Talvez, se houver demanda'],
  },
  {
    id: 'q15-3',
    sectionNumber: 15,
    sectionName: 'Expansão e Plataformização',
    questionText: 'Quais serviços do seu escritório teriam maior potencial para serem "produtizados" e oferecidos digitalmente?',
    responseType: 'checkbox',
    required: true,
    options: ['Consultoria pontual', 'Análise de documentos', 'Elaboração de pareceres', 'Cálculos tributários', 'Treinamentos/Cursos', 'Nenhum específico', 'Outros'],
  },
  {
    id: 'q15-4',
    sectionNumber: 15,
    sectionName: 'Expansão e Plataformização',
    questionText: 'Como você enxerga a evolução do mercado tributário nos próximos anos?',
    responseType: 'checkbox',
    required: true,
    options: ['Mais digitalizado', 'Mais competitivo', 'Mais focado em consultoria', 'Demanda por soluções mais rápidas', 'Globalização', 'Outras tendências'],
  },
  {
    id: 'q15-5',
    sectionNumber: 15,
    sectionName: 'Expansão e Plataformização',
    questionText: 'Haveria interesse em uma plataforma unificada para gerenciar licenciados ou franqueados no futuro?',
    responseType: 'radio',
    required: true,
    options: ['Alto', 'Médio', 'Baixo', 'Nenhum'],
  },
  {
    id: 'q15-6',
    sectionNumber: 15,
    sectionName: 'Expansão e Plataformização',
    questionText: 'Qual o maior benefício que uma plataforma unificada traria para seu modelo de expansão?',
    responseType: 'radio',
    required: true,
    options: ['Padronização de serviços', 'Redução de custos', 'Escalabilidade do negócio', 'Melhora na qualidade', 'Facilidade de gestão', 'Atração de talentos', 'Outro'],
  },

  // SEÇÃO 16: Agentes Comerciais Principais (5 perguntas)
  {
    id: 'q16-1',
    sectionNumber: 16,
    sectionName: 'Agentes Comerciais Principais',
    questionText: 'Você teria interesse em um BDR Virtual Especializado (para qualificação e pré-venda)?',
    responseType: 'radio',
    required: true,
    options: ['Sim', 'Não', 'Em avaliação'],
  },
  {
    id: 'q16-2',
    sectionNumber: 16,
    sectionName: 'Agentes Comerciais Principais',
    questionText: 'Você teria interesse em um SDR Virtual (para geração e nutrição de leads)?',
    responseType: 'radio',
    required: true,
    options: ['Sim', 'Não', 'Em avaliação'],
  },
  {
    id: 'q16-3',
    sectionNumber: 16,
    sectionName: 'Agentes Comerciais Principais',
    questionText: 'Você teria interesse em um Closer Virtual (para fechamento de vendas de serviços padronizados)?',
    responseType: 'radio',
    required: true,
    options: ['Sim', 'Não', 'Em avaliação'],
  },
  {
    id: 'q16-4',
    sectionNumber: 16,
    sectionName: 'Agentes Comerciais Principais',
    questionText: 'Você teria interesse em um Customer Success Virtual (para onboarding e retenção de clientes)?',
    responseType: 'radio',
    required: true,
    options: ['Sim', 'Não', 'Em avaliação'],
  },
  {
    id: 'q16-5',
    sectionNumber: 16,
    sectionName: 'Agentes Comerciais Principais',
    questionText: 'Qual seria a sequência ideal de implementação destes agentes comerciais virtuais no seu escritório?',
    responseType: 'text', // Usado 'text' para permitir ordenação numérica para "ranking"
    required: true,
    placeholder: 'Ordene de 1 a 4 (1=1º a implementar): BDR, SDR, Closer, Customer Success.',
  },

  // SEÇÃO 17: Agentes Avançados (5 perguntas)
  {
    id: 'q17-1',
    sectionNumber: 17,
    sectionName: 'Agentes Avançados',
    questionText: 'Você teria interesse em um Analisador de Documentos Fiscais com IA (para identificar inconsistências)?',
    responseType: 'radio',
    required: true,
    options: ['Sim', 'Não', 'Em avaliação'],
  },
  {
    id: 'q17-2',
    sectionNumber: 17,
    sectionName: 'Agentes Avançados',
    questionText: 'Você teria interesse em um Gerador de Relatórios Técnicos (para pareceres, laudos, petições automatizadas)?',
    responseType: 'radio',
    required: true,
    options: ['Sim', 'Não', 'Em avaliação'],
  },
  {
    id: 'q17-3',
    sectionNumber: 17,
    sectionName: 'Agentes Avançados',
    questionText: 'Você teria interesse em um Monitor Legislativo (para acompanhar mudanças na legislação em tempo real)?',
    responseType: 'radio',
    required: true,
    options: ['Sim', 'Não', 'Em avaliação'],
  },
  {
    id: 'q17-4',
    sectionNumber: 17,
    sectionName: 'Agentes Avançados',
    questionText: 'Qual a prioridade de implementação para estes agentes avançados no seu escritório?',
    responseType: 'text', // Usado 'text' para permitir ordenação numérica para "ranking"
    required: true,
    placeholder: 'Ordene de 1 a 3 (1=mais prioritário): Analisador, Gerador, Monitor.',
  },
  {
    id: 'q17-5',
    sectionNumber: 17,
    sectionName: 'Agentes Avançados',
    questionText: 'Qual a sua expectativa de orçamento para investir em agentes avançados de IA (anual)?',
    responseType: 'radio',
    required: true,
    options: ['Até R$10.000', 'R$10.001 - R$50.000', 'R$50.001 - R$100.000', 'Acima de R$100.000', 'Não tenho previsão'],
  },
];
